name: Build and push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: zalando/spilo
          ref: 2.1-p6

      - name: Become one with the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          # This version gets updated when spilo adds support for a new postgres version
          APP_NAME=spilo-14
          VERSION=$(git describe --tags --always --dirty)
          IMAGE_BASE=ghcr.io/finn-no/$APP_NAME
          IMAGE_NAME=$IMAGE_BASE:$VERSION
          LATEST=$IMAGE_BASE:latest

          docker build -t $IMAGE_NAME --build-arg ADDITIONAL_LOCALES="nb_NO en_GB" postgres-appliance
          docker tag $IMAGE_NAME $LATEST

          docker push $IMAGE_NAME
          docker push $LATEST
