name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: zalando/spilo
          ref: 2.1-p4

      - name: Build and tag
        run: |
          VERSION=$(git describe --tags --always --dirty)
          docker build -t tester:$VERSION
          docker tag tester:$VERSION tester:latest
